//
// Auto-generated by common-type, do not edit manually
//

import { Consent, NumberEnum, Person } from '.'

export interface BaseAddress {
  address1: string
  address2?: string
  /**
   * asdf
   *
   * la la la
   */
  ts?: number
  /**
   * @validationType integer
   */
  int?: number
  home?: boolean
  a1?: string[]
  a2?: string[][]
  o1?: {
    a: string
    b: number
  }
  p?: Person
  c?: Consent
  n?: NumberEnum
}
