//
// Auto-generated by @naturalcycles/json-schema-lib, do not edit manually
//

import { Goal, LHStatus, OvulationStatus, PregnancyTestStatus, UFCode, UFColor } from '.'

export interface BaseColorCode {
  date: string
  color: UFColor
  redscale?: number
  code: UFCode
  cd: number
  nCycle: number
  goal: Goal
  lhStatus?: LHStatus
  ovulationStatus?: OvulationStatus
  pregnancyTestStatus?: PregnancyTestStatus
}
