//
// Auto-generated by @naturalcycles/json-schema-lib, do not edit manually
//

import { CurrentPhaseId, DataFlag, Libido } from '.'

export interface CurrentPhase {
  id: CurrentPhaseId
  trackersGeneric?: boolean
  dataFlags: DataFlag[]
  libido?: Libido
}
