//
// Auto-generated by common-type, do not edit manually
//

export interface CycleSummary {
  startDate: string
  endDate: string
  nCycle: number
  cycleLength: number
  mensLength: number
  ovulationCD?: number
  ovulationDate?: string
  spottingDays?: number
  lhTestPositive?: number
  lhTestNegative?: number
  unprotectedSex?: number
  pregnancyEndDate?: string
}
