//
// Auto-generated by @naturalcycles/json-schema-lib, do not edit manually
//

import { PersonPartial, PersonRequired } from '.'

export interface TestPartialType {
  part?: PersonPartial
  req?: PersonRequired
}
