//
// Auto-generated by common-type, do not edit manually
//

import { OvulationPrediction } from '.'

export interface UFCode {
  checkLh?: boolean
  checkPreg?: boolean
  defMisc?: boolean
  defPreg?: boolean
  mens?: boolean
  /**
   * Confirmed ovulation (if in the past).
   * In the future - we don't use it:)
   */
  ovulation?: boolean
  /**
   * Frontend-only field to display "OvulationWindow'.
   */
  ovulationPrediction?: OvulationPrediction
  possMisc?: boolean
  possPreg?: boolean
}
