//
// Auto-generated by @naturalcycles/json-schema-lib, do not edit manually
//

import { BaseColorCode, DataFlag, DataQuantity } from '.'

export type UFPredictionColorCode = {
  dataFlags?: DataFlag[]
  mensQuantity?: DataQuantity
} & BaseColorCode
