//
// Auto-generated by common-type, do not edit manually
//

export interface UserFertilityStats {
  lowTempMean?: number
  lowTempRMS?: number
  highTempMean?: number
  highTempRMS?: number
  pregTempMean?: number
  pregTempRMS?: number
}
