//
// Auto-generated by @naturalcycles/json-schema-lib, do not edit manually
//

export interface UserFertilityStats {
  lowTempMean?: number
  lowTempRMS?: number
  highTempMean?: number
  highTempRMS?: number
  pregTempMean?: number
  pregTempRMS?: number
}
